name: Publish
on:
    release:
        types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: true

      - name: Generates the icons components
        run: pnpm generate:icons

      - name: Run Prettier format
        run: pnpm format

      - name: Run Prettier lint
        run: pnpm lint

      - name: Build the package
        run: pnpm package
        env:
          TAG_NAME: ${{ github.ref_name }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release Version ${{ github.ref_name }}
          branch: main
      - run: git -c user.email="actions@github.com" -c user.name="GitHub Actions" tag -fa ${{ github.ref_name }} -m "${{ github.ref_name }}"
      - run: git push -f origin ${{ github.ref_name }}
      - run: pnpm -r publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
